apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs4
spec:
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - nolock
  nfs:
    server: {{ .Values.NFS4_SERVER }}
    path: {{ .Values.NFS4_PATH }}
